((nil . ((cider-clojure-cli-aliases . ":dev:test")
         (cider-clojure-cli-parameters . "")
         (cider-ns-refresh-before-fn . "phlegyas.components/stop-system!")
         (cider-ns-refresh-after-fn . "phlegyas.components/start-system!")
         (cider-preferred-build-tool . clojure-cli))))
